export const INVENTORY_IMPORT_HEADERS = [
  "Objekt-ID",
  "Inventarnummer",
  "STIX-ID",
  "Name",
  "Kategorie",
  "Unterkategorie",
  "Hersteller",
  "Typ/Modell",
  "Seriennummer",
  "Fahrzeug-Ident.-Nr.",
  "Kennzeichen",
  "Status",
  "Lagerobjekt",
  "Einheit",
  "Anfangsbestand",
  "Aktueller Bestand",
  "Containerobjekt",
  "Liegt in Container Objekt-ID",
  "Verantwortlich Typ",
  "Mitarbeiter Vorname",
  "Mitarbeiter Nachname",
  "Weiterer Mitarbeiter 1 Vorname",
  "Weiterer Mitarbeiter 1 Nachname",
  "Weiterer Mitarbeiter 2 Vorname",
  "Weiterer Mitarbeiter 2 Nachname",
  "Weiterer Mitarbeiter 3 Vorname",
  "Weiterer Mitarbeiter 3 Nachname",
  "Kolonne",
  "Baustelle Projektnummer",
  "Baujahr/Datum",
  "Erstzulassung",
  "Erhalten am",
  "Gekauft am",
  "Gekauft bei",
  "Rechnungsnummer",
  "Lieferscheinnummer",
  "Achsen",
  "Zul. Gesamtmasse (F1) kg",
  "Nutzlast t",
  "Antrieb",
  "Aufnahmetyp",
  "Kraftstofftank l",
  "Kraftstoffart",
  "Arbeitsmitteltank l",
  "Verrechnungssatz EUR je Einheit",
  "Verrechnungssatz stillgelegt EUR je Einheit",
  "Versichert bei",
  "Versicherung p.a. netto EUR",
  "Letzter Service Datum",
  "Letzter Service H",
  "Letzter Service KM",
  "Nächster Service Datum",
  "Nächster Service H",
  "Nächster Service KM",
  "Letzte DGUV",
  "Nächste DGUV",
  "Letzte TÜV",
  "Nächste TÜV",
  "Letzte HU",
  "Nächste HU",
  "Letzte Tachoprüfung",
  "Nächste Tachoprüfung",
  "Letzte SP",
  "Nächste SP",
  "Letzte ADR",
  "Nächste ADR",
  "Notizen",
  "Ansprechpartner Firma",
  "Ansprechpartner Rolle",
  "Ansprechpartner Anrede",
  "Ansprechpartner Vorname",
  "Ansprechpartner Nachname",
  "Ansprechpartner Telefon",
  "Ansprechpartner Mobil",
  "Ansprechpartner E-Mail",
  "Ansprechpartner Webseite",
  "Ansprechpartner Notizen",
] as const;

// Contiguous column ranges (by header name), labeled with the exact same
// tile/section names used in the Inventarobjekt-Formular (InventoryItemForm.tsx),
// so the spreadsheet groups read the same as the app. Kept in sync with the
// header order above by referencing header text rather than indexes.
//
// Because the Excel column order can't be changed (existing filled-in files
// depend on it) while the form's field order differs, two app tiles end up
// split into two separate ranges each: "Hersteller / Modell" and
// "Kennzeichnung" both appear twice below, once for each place their fields
// land in the fixed column order. Columns not covered by any range stay
// always visible (not collapsible): the core identity fields and Status.
export const INVENTORY_IMPORT_COLUMN_GROUPS: {
  label: string;
  from: string;
  to: string;
}[] = [
  { label: "Kategorie", from: "Kategorie", to: "Unterkategorie" },
  { label: "Hersteller / Modell", from: "Hersteller", to: "Typ/Modell" },
  {
    label: "Kennzeichnung",
    from: "Seriennummer",
    to: "Kennzeichen",
  },
  {
    label: "Einheit, Container und Lager",
    from: "Lagerobjekt",
    to: "Liegt in Container Objekt-ID",
  },
  {
    label: "Zuordnung",
    from: "Verantwortlich Typ",
    to: "Baustelle Projektnummer",
  },
  {
    label: "Hersteller / Modell",
    from: "Baujahr/Datum",
    to: "Erhalten am",
  },
  {
    label: "Beschaffung",
    from: "Gekauft am",
    to: "Lieferscheinnummer",
  },
  {
    label: "Fahrzeug-, LKW- und Gerätedaten",
    from: "Achsen",
    to: "Arbeitsmitteltank l",
  },
  {
    label: "Controlling",
    from: "Verrechnungssatz EUR je Einheit",
    to: "Verrechnungssatz stillgelegt EUR je Einheit",
  },
  {
    label: "Versicherung",
    from: "Versichert bei",
    to: "Versicherung p.a. netto EUR",
  },
  { label: "Service", from: "Letzter Service Datum", to: "Nächster Service KM" },
  { label: "Prüfungen", from: "Letzte DGUV", to: "Nächste ADR" },
  { label: "Dokumentation", from: "Notizen", to: "Ansprechpartner Notizen" },
];
