export const INVENTORY_IMPORT_HEADERS = [
  "Objekt-ID",
  "Inventarnummer",
  "STIX-ID",
  "Name",
  "Kategorie",
  "Unterkategorie",
  "Hersteller",
  "Typ/Modell",
  "Seriennummer",
  "Fahrzeug-Ident.-Nr.",
  "Kennzeichen",
  "Status",
  "Lagerobjekt",
  "Einheit",
  "Anfangsbestand",
  "Aktueller Bestand",
  "Containerobjekt",
  "Liegt in Container Objekt-ID",
  "Verantwortlich Typ",
  "Mitarbeiter Vorname",
  "Mitarbeiter Nachname",
  "Weiterer Mitarbeiter 1 Vorname",
  "Weiterer Mitarbeiter 1 Nachname",
  "Weiterer Mitarbeiter 2 Vorname",
  "Weiterer Mitarbeiter 2 Nachname",
  "Weiterer Mitarbeiter 3 Vorname",
  "Weiterer Mitarbeiter 3 Nachname",
  "Kolonne",
  "Baustelle Projektnummer",
  "Baujahr/Datum",
  "Erstzulassung",
  "Erhalten am",
  "Gekauft am",
  "Gekauft bei",
  "Rechnungsnummer",
  "Lieferscheinnummer",
  "Achsen",
  "Zul. Gesamtmasse (F1) kg",
  "Nutzlast t",
  "Antrieb",
  "Aufnahmetyp",
  "Kraftstofftank l",
  "Kraftstoffart",
  "Arbeitsmitteltank l",
  "Verrechnungssatz EUR je Einheit",
  "Verrechnungssatz stillgelegt EUR je Einheit",
  "Versichert bei",
  "Versicherung p.a. netto EUR",
  "Letzter Service Datum",
  "Letzter Service H",
  "Letzter Service KM",
  "Nächster Service Datum",
  "Nächster Service H",
  "Nächster Service KM",
  "Letzte DGUV",
  "Nächste DGUV",
  "Letzte TÜV",
  "Nächste TÜV",
  "Letzte HU",
  "Nächste HU",
  "Letzte Tachoprüfung",
  "Nächste Tachoprüfung",
  "Letzte SP",
  "Nächste SP",
  "Letzte ADR",
  "Nächste ADR",
  "Notizen",
  "Ansprechpartner Firma",
  "Ansprechpartner Rolle",
  "Ansprechpartner Anrede",
  "Ansprechpartner Vorname",
  "Ansprechpartner Nachname",
  "Ansprechpartner Telefon",
  "Ansprechpartner Mobil",
  "Ansprechpartner E-Mail",
  "Ansprechpartner Webseite",
  "Ansprechpartner Notizen",
] as const;
