export const PROJECT_IMPORT_HEADERS = [
  "Projektnummer",
  "Name",
  "Auftraggeber",
  "Bauleiter 1",
  "Bauleiter 2",
  "Bauleiter 3",
  "Status",
  "Geplanter Start",
  "Geplantes Ende",
  "Tatsächlicher Start",
  "Tatsächliches Ende",
  "Verbleibende Bauzeit",
  "Baustellenadresse",
  "DVGW",
  "Gütezeichen Kanalbau",
  "Lieferscheine",
  "Auftragssumme netto EUR",
  "Nachträge netto EUR",
  "Fortschritt %",
  "Zahlungen netto EUR",
  "Schlussrechnung erstellt",
  "Schlussrechnungsnummer",
  "Schlussrechnung netto EUR",
  "Notizen",
] as const;
